max_epoch: 100
batch_type: folded
batch_size: 72
init: xavier_uniform
patience: 3

val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1

optim: adam
optim_conf:
    lr: 0.001

scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000

# encoder: vgg_rnn
encoder: transducer
encoder_conf:
    rnn_type: lstm
    bidirectional: true
    use_projection: false
    num_layers: 4
    hidden_size: 320
    output_size: 320
    dropout: 0.4

decoder: transducer
decoder_conf:
    rnn_type: lstm
    num_layers: 1
    hidden_size: 256
    dropout_embed: 0.2
    dropout: 0.2
joint_net_conf:
    joint_space_size: 256
    joint_activation_type: tanh
